[package]
name = "giga-chess"
description = "A rust chess library built for performance, handling game logic and legal/best move generation."
version = "0.6.0"
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://github.com/Zitronenjoghurt/giga-chess"

[dependencies]
chrono = "0.4.41"
rand = "0.9.1"
rayon = "1.10.0"

[dev-dependencies]
criterion = { version = "0.6", features = ["html_reports"] }

[[bench]]
name = "benchmark"
harness = false

[[bin]]
name = "magic-numbers"
path = "bin/magic_numbers.rs"
