use crate::impl_bit_vec_header;
use crate::storage::io::{BitDecode, BitEncode, BitReader, BitWriter};
use std::fmt;
use std::io::{Read, Write};
use std::str::FromStr;

#[derive(Debug, Copy, Clone, PartialEq, Eq, Hash)]
#[repr(u8)]
pub enum LichessPuzzleTheme {
    Short = 0b0000000,
    Endgame = 0b0000001,
    Middlegame = 0b0000010,
    Crushing = 0b0000011,
    Mate = 0b0000100,
    Advantage = 0b0000101,
    Long = 0b0000110,
    OneMove = 0b0000111,
    MateIn1 = 0b0001000,
    Master = 0b0001001,
    MateIn2 = 0b0001010,
    Fork = 0b0001011,
    KingsideAttack = 0b0001100,
    VeryLong = 0b0001101,
    Sacrifice = 0b0001110,
    AdvancedPawn = 0b0001111,
    DefensiveMove = 0b0010000,
    Pin = 0b0010001,
    RookEndgame = 0b0010010,
    DiscoveredAttack = 0b0010011,
    Opening = 0b0010100,
    Deflection = 0b0010101,
    QuietMove = 0b0010110,
    PawnEndgame = 0b0010111,
    HangingPiece = 0b0011000,
    Attraction = 0b0011001,
    BackRankMate = 0b0011010,
    MateIn3 = 0b0011011,
    ExposedKing = 0b0011100,
    Promotion = 0b0011101,
    Skewer = 0b0011110,
    DiscoveredCheck = 0b0011111,
    QueensideAttack = 0b0100000,
    BishopEndgame = 0b0100001,
    Clearance = 0b0100010,
    MasterVsMaster = 0b0100011,
    Intermezzo = 0b0100100,
    QueenEndgame = 0b0100101,
    PillsburysMate = 0b0100110,
    TrappedPiece = 0b0100111,
    OperaMate = 0b0101000,
    Zugzwang = 0b0101001,
    KnightEndgame = 0b0101010,
    QueenRookEndgame = 0b0101011,
    AttackingF2F7 = 0b0101100,
    CapturingDefender = 0b0101101,
    DoubleCheck = 0b0101110,
    MateIn4 = 0b0101111,
    SmotheredMate = 0b0110000,
    EpauletteMate = 0b0110001,
    Interference = 0b0110010,
    XRayAttack = 0b0110011,
    Equality = 0b0110100,
    CornerMate = 0b0110101,
    HookMate = 0b0110110,
    EnPassant = 0b0110111,
    SwallowstailMate = 0b0111000,
    TriangleMate = 0b0111001,
    CollinearMove = 0b0111010,
    ArabianMate = 0b0111011,
    AnastasiaMate = 0b0111100,
    MorphysMate = 0b0111101,
    BlindSwineMate = 0b0111110,
    MateIn5 = 0b0111111,
    KillBoxMate = 0b1000000,
    DovetailMate = 0b1000001,
    BodenMate = 0b1000010,
    DoubleBishopMate = 0b1000011,
    SuperGM = 0b1000100,
    Castling = 0b1000101,
    VukovicMate = 0b1000110,
    BalestraMate = 0b1000111,
    UnderPromotion = 0b1001000,
}

impl LichessPuzzleTheme {
    pub fn from_bits(bits: u8) -> Option<Self> {
        if bits <= 72 {
            // SAFETY: Because LichessPuzzleTheme is #[repr(u8)] and we've bounds-checked
            // that `bits` strictly falls within the valid range (0..=72).
            Some(unsafe { std::mem::transmute::<u8, Self>(bits) })
        } else {
            None
        }
    }

    /// Helper to grab the exact string representation
    const fn as_str(&self) -> &'static str {
        match self {
            Self::Short => "short",
            Self::Endgame => "endgame",
            Self::Middlegame => "middlegame",
            Self::Crushing => "crushing",
            Self::Mate => "mate",
            Self::Advantage => "advantage",
            Self::Long => "long",
            Self::OneMove => "oneMove",
            Self::MateIn1 => "mateIn1",
            Self::Master => "master",
            Self::MateIn2 => "mateIn2",
            Self::Fork => "fork",
            Self::KingsideAttack => "kingsideAttack",
            Self::VeryLong => "veryLong",
            Self::Sacrifice => "sacrifice",
            Self::AdvancedPawn => "advancedPawn",
            Self::DefensiveMove => "defensiveMove",
            Self::Pin => "pin",
            Self::RookEndgame => "rookEndgame",
            Self::DiscoveredAttack => "discoveredAttack",
            Self::Opening => "opening",
            Self::Deflection => "deflection",
            Self::QuietMove => "quietMove",
            Self::PawnEndgame => "pawnEndgame",
            Self::HangingPiece => "hangingPiece",
            Self::Attraction => "attraction",
            Self::BackRankMate => "backRankMate",
            Self::MateIn3 => "mateIn3",
            Self::ExposedKing => "exposedKing",
            Self::Promotion => "promotion",
            Self::Skewer => "skewer",
            Self::DiscoveredCheck => "discoveredCheck",
            Self::QueensideAttack => "queensideAttack",
            Self::BishopEndgame => "bishopEndgame",
            Self::Clearance => "clearance",
            Self::MasterVsMaster => "masterVsMaster",
            Self::Intermezzo => "intermezzo",
            Self::QueenEndgame => "queenEndgame",
            Self::PillsburysMate => "pillsburysMate",
            Self::TrappedPiece => "trappedPiece",
            Self::OperaMate => "operaMate",
            Self::Zugzwang => "zugzwang",
            Self::KnightEndgame => "knightEndgame",
            Self::QueenRookEndgame => "queenRookEndgame",
            Self::AttackingF2F7 => "attackingF2F7",
            Self::CapturingDefender => "capturingDefender",
            Self::DoubleCheck => "doubleCheck",
            Self::MateIn4 => "mateIn4",
            Self::SmotheredMate => "smotheredMate",
            Self::EpauletteMate => "epauletteMate",
            Self::Interference => "interference",
            Self::XRayAttack => "xRayAttack",
            Self::Equality => "equality",
            Self::CornerMate => "cornerMate",
            Self::HookMate => "hookMate",
            Self::EnPassant => "enPassant",
            Self::SwallowstailMate => "swallowstailMate",
            Self::TriangleMate => "triangleMate",
            Self::CollinearMove => "collinearMove",
            Self::ArabianMate => "arabianMate",
            Self::AnastasiaMate => "anastasiaMate",
            Self::MorphysMate => "morphysMate",
            Self::BlindSwineMate => "blindSwineMate",
            Self::MateIn5 => "mateIn5",
            Self::KillBoxMate => "killBoxMate",
            Self::DovetailMate => "dovetailMate",
            Self::BodenMate => "bodenMate",
            Self::DoubleBishopMate => "doubleBishopMate",
            Self::SuperGM => "superGM",
            Self::Castling => "castling",
            Self::VukovicMate => "vukovicMate",
            Self::BalestraMate => "balestraMate",
            Self::UnderPromotion => "underPromotion",
        }
    }

    pub const ALL: [LichessPuzzleTheme; 73] = [
        Self::Short,
        Self::Endgame,
        Self::Middlegame,
        Self::Crushing,
        Self::Mate,
        Self::Advantage,
        Self::Long,
        Self::OneMove,
        Self::MateIn1,
        Self::Master,
        Self::MateIn2,
        Self::Fork,
        Self::KingsideAttack,
        Self::VeryLong,
        Self::Sacrifice,
        Self::AdvancedPawn,
        Self::DefensiveMove,
        Self::Pin,
        Self::RookEndgame,
        Self::DiscoveredAttack,
        Self::Opening,
        Self::Deflection,
        Self::QuietMove,
        Self::PawnEndgame,
        Self::HangingPiece,
        Self::Attraction,
        Self::BackRankMate,
        Self::MateIn3,
        Self::ExposedKing,
        Self::Promotion,
        Self::Skewer,
        Self::DiscoveredCheck,
        Self::QueensideAttack,
        Self::BishopEndgame,
        Self::Clearance,
        Self::MasterVsMaster,
        Self::Intermezzo,
        Self::QueenEndgame,
        Self::PillsburysMate,
        Self::TrappedPiece,
        Self::OperaMate,
        Self::Zugzwang,
        Self::KnightEndgame,
        Self::QueenRookEndgame,
        Self::AttackingF2F7,
        Self::CapturingDefender,
        Self::DoubleCheck,
        Self::MateIn4,
        Self::SmotheredMate,
        Self::EpauletteMate,
        Self::Interference,
        Self::XRayAttack,
        Self::Equality,
        Self::CornerMate,
        Self::HookMate,
        Self::EnPassant,
        Self::SwallowstailMate,
        Self::TriangleMate,
        Self::CollinearMove,
        Self::ArabianMate,
        Self::AnastasiaMate,
        Self::MorphysMate,
        Self::BlindSwineMate,
        Self::MateIn5,
        Self::KillBoxMate,
        Self::DovetailMate,
        Self::BodenMate,
        Self::DoubleBishopMate,
        Self::SuperGM,
        Self::Castling,
        Self::VukovicMate,
        Self::BalestraMate,
        Self::UnderPromotion,
    ];
}

impl fmt::Display for LichessPuzzleTheme {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl FromStr for LichessPuzzleTheme {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "short" => Ok(Self::Short),
            "endgame" => Ok(Self::Endgame),
            "middlegame" => Ok(Self::Middlegame),
            "crushing" => Ok(Self::Crushing),
            "mate" => Ok(Self::Mate),
            "advantage" => Ok(Self::Advantage),
            "long" => Ok(Self::Long),
            "oneMove" => Ok(Self::OneMove),
            "mateIn1" => Ok(Self::MateIn1),
            "master" => Ok(Self::Master),
            "mateIn2" => Ok(Self::MateIn2),
            "fork" => Ok(Self::Fork),
            "kingsideAttack" => Ok(Self::KingsideAttack),
            "veryLong" => Ok(Self::VeryLong),
            "sacrifice" => Ok(Self::Sacrifice),
            "advancedPawn" => Ok(Self::AdvancedPawn),
            "defensiveMove" => Ok(Self::DefensiveMove),
            "pin" => Ok(Self::Pin),
            "rookEndgame" => Ok(Self::RookEndgame),
            "discoveredAttack" => Ok(Self::DiscoveredAttack),
            "opening" => Ok(Self::Opening),
            "deflection" => Ok(Self::Deflection),
            "quietMove" => Ok(Self::QuietMove),
            "pawnEndgame" => Ok(Self::PawnEndgame),
            "hangingPiece" => Ok(Self::HangingPiece),
            "attraction" => Ok(Self::Attraction),
            "backRankMate" => Ok(Self::BackRankMate),
            "mateIn3" => Ok(Self::MateIn3),
            "exposedKing" => Ok(Self::ExposedKing),
            "promotion" => Ok(Self::Promotion),
            "skewer" => Ok(Self::Skewer),
            "discoveredCheck" => Ok(Self::DiscoveredCheck),
            "queensideAttack" => Ok(Self::QueensideAttack),
            "bishopEndgame" => Ok(Self::BishopEndgame),
            "clearance" => Ok(Self::Clearance),
            "masterVsMaster" => Ok(Self::MasterVsMaster),
            "intermezzo" => Ok(Self::Intermezzo),
            "queenEndgame" => Ok(Self::QueenEndgame),
            "pillsburysMate" => Ok(Self::PillsburysMate),
            "trappedPiece" => Ok(Self::TrappedPiece),
            "operaMate" => Ok(Self::OperaMate),
            "zugzwang" => Ok(Self::Zugzwang),
            "knightEndgame" => Ok(Self::KnightEndgame),
            "queenRookEndgame" => Ok(Self::QueenRookEndgame),
            "attackingF2F7" => Ok(Self::AttackingF2F7),
            "capturingDefender" => Ok(Self::CapturingDefender),
            "doubleCheck" => Ok(Self::DoubleCheck),
            "mateIn4" => Ok(Self::MateIn4),
            "smotheredMate" => Ok(Self::SmotheredMate),
            "epauletteMate" => Ok(Self::EpauletteMate),
            "interference" => Ok(Self::Interference),
            "xRayAttack" => Ok(Self::XRayAttack),
            "equality" => Ok(Self::Equality),
            "cornerMate" => Ok(Self::CornerMate),
            "hookMate" => Ok(Self::HookMate),
            "enPassant" => Ok(Self::EnPassant),
            "swallowstailMate" => Ok(Self::SwallowstailMate),
            "triangleMate" => Ok(Self::TriangleMate),
            "collinearMove" => Ok(Self::CollinearMove),
            "arabianMate" => Ok(Self::ArabianMate),
            "anastasiaMate" => Ok(Self::AnastasiaMate),
            "morphysMate" => Ok(Self::MorphysMate),
            "blindSwineMate" => Ok(Self::BlindSwineMate),
            "mateIn5" => Ok(Self::MateIn5),
            "killBoxMate" => Ok(Self::KillBoxMate),
            "dovetailMate" => Ok(Self::DovetailMate),
            "bodenMate" => Ok(Self::BodenMate),
            "doubleBishopMate" => Ok(Self::DoubleBishopMate),
            "superGM" => Ok(Self::SuperGM),
            "castling" => Ok(Self::Castling),
            "vukovicMate" => Ok(Self::VukovicMate),
            "balestraMate" => Ok(Self::BalestraMate),
            "underPromotion" => Ok(Self::UnderPromotion),
            _ => Err(format!("Unrecognized Lichess puzzle theme: {}", s)),
        }
    }
}

impl BitEncode for LichessPuzzleTheme {
    fn encode<W: Write>(&self, w: &mut BitWriter<W>) -> std::io::Result<()> {
        w.write_bits(*self as u8, 7)
    }
}

impl BitDecode for LichessPuzzleTheme {
    fn decode<R: Read>(r: &mut BitReader<R>) -> std::io::Result<Self> {
        let bits = r.read_bits(7)?;
        LichessPuzzleTheme::from_bits(bits).ok_or_else(|| {
            std::io::Error::new(
                std::io::ErrorKind::InvalidData,
                format!("Invalid Lichess puzzle theme bits: {bits}"),
            )
        })
    }
}

impl_bit_vec_header!(u8, LichessPuzzleTheme);
